In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)

In [3]:
# File paths
pop_path = "../data/raw/japan_total_population.csv"
elderly_path = "../data/raw/japan_elderly_percent.csv"
gdp_path = "../data/raw/japan_gdp.csv"
fertility_path = "../data/raw/japan_fertility_rate.csv"

# Load CSVs (skip first 4 metadata rows)
pop = pd.read_csv(pop_path, skiprows=4)
elderly = pd.read_csv(elderly_path, skiprows=4)
gdp = pd.read_csv(gdp_path, skiprows=4)
fertility = pd.read_csv(fertility_path, skiprows=4)

pop.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,Unnamed: 69
0,Aruba,ABW,"Population, total",SP.POP.TOTL,54922.0,55578.0,56320.0,57002.0,57619.0,58190.0,58694.0,58990.0,59069.0,59052.0,58950.0,58781.0,58047.0,58299.0,58349.0,58295.0,58368.0,58580.0,58776.0,59191.0,59909.0,60563.0,61276.0,62228.0,62901.0,61728.0,59931.0,59159.0,59331.0,60443.0,62753.0,65896.0,69005.0,73685.0,77595.0,79805.0,83021.0,86301.0,88451.0,89659.0,90588.0,91439.0,92074.0,93128.0,95138.0,97635.0,99405.0,100150.0,100917.0,101604.0,101838.0,102591.0,104110.0,105675.0,106807.0,107906.0,108727.0,108735.0,108908.0,109203.0,108587.0,107700.0,107310.0,107359.0,107995.0,NaN
1,Africa Eastern and Southern,AFE,"Population, total",SP.POP.TOTL,130075728.0,133534923.0,137171659.0,140945536.0,144904094.0,149033472.0,153281203.0,157704381.0,162329396.0,167088245.0,171984985.0,177022314.0,182126556.0,187524135.0,193186642.0,198914573.0,204802976.0,210680842.0,217074286.0,223974122.0,230792729.0,238043099.0,245822010.0,253644643.0,261458202.0,269450407.0,277621771.0,286067346.0,294498625.0,302939121.0,311748681.0,320442961.0,329082707.0,338324002.0,347441809.0,356580375.0,366138524.0,375646235.0,385505757.0,395750933.0,406156661.0,416807868.0,427820358.0,439173286.0,450928044.0,463076637.0,475606210.0,488580707.0,502070763.0,516003448.0,530308387.0,544737983.0,559609961.0,575202699.0,590968990.0,607123269.0,623369401.0,640058741.0,657801085.0,675950189.0,694446100.0,713090928.0,731821393.0,750491370.0,769280888.0,NaN
2,Afghanistan,AFG,"Population, total",SP.POP.TOTL,9035043.0,9214083.0,9404406.0,9604487.0,9814318.0,10036008.0,10266395.0,10505959.0,10756922.0,11017409.0,11290128.0,11567667.0,11853696.0,12157999.0,12469127.0,12773954.0,13059851.0,13340756.0,13611441.0,13655567.0,13169311.0,11937581.0,10991378.0,10917982.0,11190221.0,11426852.0,11420074.0,11387818.0,11523298.0,11874088.0,12045660.0,12238879.0,13278974.0,14943172.0,16250794.0,17065836.0,17763266.0,18452091.0,19159996.0,19887785.0,20130327.0,20284307.0,21378117.0,22733049.0,23560654.0,24404567.0,25424094.0,25909852.0,26482622.0,27466101.0,28284089.0,29347708.0,30560034.0,31622704.0,32792523.0,33831764.0,34700612.0,35688935.0,36743039.0,37856121.0,39068979.0,40000412.0,40578842.0,41454761.0,42647492.0,NaN
3,Africa Western and Central,AFW,"Population, total",SP.POP.TOTL,97630925.0,99706674.0,101854756.0,104089175.0,106388440.0,108772632.0,111246953.0,113795019.0,116444636.0,119203521.0,122086536.0,125072948.0,128176494.0,131449942.0,134911581.0,138569918.0,142337272.0,146258576.0,150402616.0,154721711.0,159166518.0,163762473.0,168585118.0,173255157.0,177880746.0,182811038.0,187889141.0,193104347.0,198485027.0,204062274.0,209566031.0,215178709.0,221191375.0,227246778.0,233360104.0,239801875.0,246415446.0,253207584.0,260297834.0,267506298.0,274968446.0,282780717.0,290841795.0,299142845.0,307725100.0,316588476.0,325663158.0,334984176.0,344586109.0,354343844.0,364358270.0,374790143.0,385360349.0,396030207.0,406992047.0,418127845.0,429454743.0,440882906.0,452195915.0,463365429.0,474569351.0,485920997.0,497387180.0,509398589.0,521764076.0,NaN
4,Angola,AGO,"Population, total",SP.POP.TOTL,5231654.0,5301583.0,5354310.0,5408320.0,5464187.0,5521981.0,5581386.0,5641807.0,5702699.0,5763685.0,5852788.0,5991102.0,6174262.0,6388528.0,6613367.0,6842947.0,7074664.0,7317829.0,7576734.0,7847207.0,8133872.0,8435607.0,8751648.0,9082983.0,9425917.0,9779120.0,10139450.0,10497858.0,10861291.0,11238562.0,11626360.0,12023529.0,12423712.0,12827135.0,13249764.0,13699778.0,14170973.0,14660413.0,15159370.0,15667235.0,16194869.0,16747208.0,17327699.0,17943712.0,18600423.0,19291161.0,20015279.0,20778561.0,21578655.0,22414773.0,23294825.0,24218352.0,25177394.0,26165620.0,27160769.0,28157798.0,29183070.0,30234839.0,31297155.0,32375632.0,33451132.0,34532429.0,35635029.0,36749906.0,37885849.0,NaN

In [4]:
pop = pop[pop["Country Name"] == "Japan"]
elderly = elderly[elderly["Country Name"] == "Japan"]
gdp = gdp[gdp["Country Name"] == "Japan"]
fertility = fertility[fertility["Country Name"] == "Japan"]

In [5]:
cols_to_drop = ["Country Name", "Country Code", 
                "Indicator Name", "Indicator Code"]

pop = pop.drop(columns=cols_to_drop)
elderly = elderly.drop(columns=cols_to_drop)
gdp = gdp.drop(columns=cols_to_drop)
fertility = fertility.drop(columns=cols_to_drop)

In [7]:
pop = pop.T
elderly = elderly.T
gdp = gdp.T
fertility = fertility.T

In [10]:
# Convert Year column safely

pop = pop[pd.to_numeric(pop["Year"], errors="coerce").notnull()]
elderly = elderly[pd.to_numeric(elderly["Year"], errors="coerce").notnull()]
gdp = gdp[pd.to_numeric(gdp["Year"], errors="coerce").notnull()]
fertility = fertility[pd.to_numeric(fertility["Year"], errors="coerce").notnull()]

# Now convert to integer
pop["Year"] = pop["Year"].astype(int)
elderly["Year"] = elderly["Year"].astype(int)
gdp["Year"] = gdp["Year"].astype(int)
fertility["Year"] = fertility["Year"].astype(int)

In [8]:
pop = pop.reset_index()
elderly = elderly.reset_index()
gdp = gdp.reset_index()
fertility = fertility.reset_index()

pop.columns = ["Year", "Total_Population"]
elderly.columns = ["Year", "Elderly_Percent"]
gdp.columns = ["Year", "GDP"]
fertility.columns = ["Year", "Fertility_Rate"]

In [11]:
pop = pop[(pop["Year"] >= 1990)]
elderly = elderly[(elderly["Year"] >= 1990)]
gdp = gdp[(gdp["Year"] >= 1990)]
fertility = fertility[(fertility["Year"] >= 1990)]

In [12]:
df = pop.merge(elderly, on="Year")
df = df.merge(gdp, on="Year")
df = df.merge(fertility, on="Year")

df.head()

   Year  Total_Population  Elderly_Percent           GDP  Fertility_Rate
0  1990       123478000.0        12.159237  3.185905e+12            1.54
1  1991       123964000.0        12.642663  3.648066e+12            1.53
2  1992       124425000.0        13.146100  3.980703e+12            1.50
3  1993       124829000.0        13.645147  4.536940e+12            1.46
4  1994       125178000.0        14.147171  4.998798e+12            1.50

In [13]:
df.isnull().sum()

Year                0
Total_Population    0
Elderly_Percent     0
GDP                 0
Fertility_Rate      1
dtype: int64

In [14]:
df = df.fillna(method="ffill")

C:\Users\jites\AppData\Local\Temp\ipykernel_38040\3441110583.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df = df.fillna(method="ffill")

In [15]:
df.to_csv("../data/processed/japan_cleaned_data.csv", index=False)